<?php
module_load_include('inc', 'drupal_site_feedback', 'includes/exceptions');

use DrupalSiteFeedback\ParseForm;
use DrupalSiteFeedback\Submission;
use DrupalSiteFeedback\WebformCaptchaException;
use DrupalSiteFeedback\WebformNotFoundException;

function drupal_site_feedback_get_form_api($form_id) {

    module_load_include('inc', 'drupal_site_feedback', 'includes/parse_form');

    try {

        $parser = new ParseForm();
        $output = [

            'type'    => 'success',
            'code'    => 1001,
            'message' => $parser->parse($form_id),
        ];

    } catch (WebformNotFoundException $e) {

        $output = [

            'type'    => 'error',
            'code'    => 1002,
            'message' => 'Could not find webform',
        ];
    }

    return drupal_json_output($output);
}

function drupal_site_feedback_post_form_api($form_id) {

    $error = [

        'type'    => 'error',
        'code'    => 1002,
        'message' => 'Could not find webform',
    ];

    if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
        return drupal_json_output($error);
    }

    $data = file_get_contents('php://input');
    $data = json_decode($data, true);

    if (!isset($data['ds_feedback'])) {
        return drupal_json_output($error);
    }

    global $user;
    module_load_include('inc', 'drupal_site_feedback', 'includes/submission');
    module_load_include('inc', 'drupal_site_feedback', 'includes/parse_form');

    try {

        $submission = new Submission();
        $submission->submit($form_id, $user->uid, $data['ds_feedback'], $data['captcha']);

        $output = [

            'type'    => 'success',
            'code'    => 1003,
            'message' => 'Submission created',
        ];

    } catch (WebformNotFoundException $e) {

        $output = $error;

    } catch (WebformCaptchaException $e) {

        $output = [

            'type'    => 'error',
            'code'    => 1004,
            'message' => 'Webform captcha not valid',
        ];
    }

    $parser = new ParseForm();
    $form   = $parser->parse($form_id);

    $output['captcha'] = $form['captcha'];

    return drupal_json_output($output);
}

function drupal_site_feedback_menu() {

    $items = [];

    $items['ds_feedback/%'] = [

        'title'           => 'Getting form in json form',
        'type'            => MENU_CALLBACK,
        'page callback'   => 'drupal_site_feedback_get_form_api',
        'page arguments'  => [1],
        'access callback' => true,
    ];

    $items['ds_feedback/%/create'] = [

        'title'           => 'Getting form in json form',
        'type'            => MENU_CALLBACK,
        'page callback'   => 'drupal_site_feedback_post_form_api',
        'page arguments'  => [1],
        'access callback' => true,
    ];

    $items['ds_feedback/demo'] = [

        'title'           => 'Getting form in json form',
        'type'            => MENU_CALLBACK,
        'page callback'   => 'drupal_site_feedback_tag',
        'page arguments'  => [1],
        'access callback' => true,
    ];

    return $items;
}

function drupal_site_feedback_theme() {

    return [

        'drupal_site_feedback_tag' => [
            'template' => 'theme/drupal-site-feedback-tag',
        ],
    ];
}

function drupal_site_feedback_tag() {

    $module_path = drupal_get_path('module', 'drupal_site_feedback');
    drupal_add_js($module_path . '/app/dist/elements/drupal-site-feedback.js.gz', ['scope' => 'footer']);

    recaptcha_captcha('generate', 'reCAPTCHA');

    return theme('drupal_site_feedback_tag', [
        'url' => url('ds_feedback/' . variable_get('drupal_site_feedback_id')),
    ]);
}

function drupal_site_feedback_preprocess_page(&$vars) {
    $vars['page']['drupal_site_feedback'] = drupal_site_feedback_tag();
}
